import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
"use client";               // 顶级布局需要转成 client component

import { motion, AnimatePresence } from "framer-motion";
import { usePathname } from "next/navigation";
export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();
  
    return (
      <html lang="en">
        <body className="min-h-screen">
          <AnimatePresence mode="wait">
            <motion.div
              key={pathname}       // 关键：根据路由变化触发 exit / enter
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.2 }}
            >
              {children}
            </motion.div>
          </AnimatePresence>
        </body>
      </html>
    );
  }

